// Authored controller contract; no model calls or private course fixtures.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map(),requests=[];
const document={activeElement:null,getElementById:id=>elements.get(id),querySelector:s=>elements.get(s.replace(/^\./,''))||null};
function node(id){const n={id,textContent:'',hidden:false,disabled:false,open:false,dataset:{},classList:{add(){}},setAttribute(){},addEventListener(){},focus(){document.activeElement=this},matches(){return this.open},hidePopover(){this.open=false},contains(){return false},insertAdjacentHTML(_pos,html){register(html)},querySelector:s=>s==='.sampling-details'?elements.get('sampling-details'):null,querySelectorAll:s=>[...elements.values()].filter(n=>s==='[data-outcome]'?n.dataset.outcome:s==='[data-tutor-policy]'?n.dataset.tutorPolicy:false)};Object.defineProperty(n,'innerHTML',{set(html){this.html=html;register(html)},get(){return this.html||''}});elements.set(id,n);return n}
function register(html){for(const m of html.matchAll(/<[^>]+>/g)){const id=m[0].match(/id="([^"]+)"/),policy=m[0].match(/data-policy="([^"]+)"/),outcome=m[0].match(/data-outcome="([^"]+)"/),tutor=m[0].match(/data-tutor-policy="([^"]+)"/);if(id||outcome||tutor){const n=node(id?.[1]||outcome&&policy[1]+':'+outcome[1]||'tutor:'+tutor[1]);n.disabled=/\sdisabled(?:\s|>)/.test(m[0]);if(policy)n.dataset.policy=policy[1];if(outcome)n.dataset.outcome=outcome[1];if(tutor)n.dataset.tutorPolicy=tutor[1]}}if(html.includes('class="sampling-details"'))node('sampling-details')}
['app','reset','view-description','chat-caption','prototype-note','explorer-heading','breadcrumb','version-captured','version-generated-description'].forEach(node);
const originals=['direct','hint'].map(id=>({id,frames:[{work:{source:'shared'}},{work:{source:id+' baseline'}}]}));
const state={encounters:structuredClone(originals),caseIndex:0,step:1};
const data={authored_demo:true,model:'authored',requested_per_condition:2,conditions:['direct','hint'].map(id=>({id,label:id,policy:'Authored policy',requested:2,valid:2,failed:0,status:'complete',categories:[{decision:'revise-work',count:2,proportion:1,interval:[0.1,1]}],samples:[1,2].map(index=>({index,decision:'revise-work',frame:{work:{source:id+' sample '+index}}}))}))};
const context=vm.createContext({document,state,structuredClone,AbortSignal,$:id=>elements.get(id),esc:String,glyph:()=>'<svg aria-hidden="true" focusable="false"></svg>',current:()=>state.encounters[state.caseIndex],notify(){},render(){},renderOperationStatus(){},fetch:async(url,opts)=>{requests.push({url,opts});return {ok:true,json:async()=>structuredClone(data)}}});
const tick=async()=>{for(let i=0;i<4;i++)await new Promise(setImmediate)};
(async()=>{vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../apps/policy-sampling.js'),'utf8'),context);await tick();
context.renderOperationStatus();assert.equal(elements.get('prototype-note').textContent,'Authored test data · No live comparison results');assert.match(elements.get('policy-sampling-summary').textContent,/No live comparison results/);assert.match(elements.get('policy-sampling-footer').innerHTML,/Configured model \(not called\)/);
elements.get('direct:revise-work').onclick();assert.equal(state.caseIndex,0);assert.equal(state.encounters[0].frames[1].work.source,'direct sample 1');assert.equal(state.encounters[1].frames[1].work.source,'hint baseline');
elements.get('policy-sample-next').onclick();assert.equal(state.encounters[0].frames[1].work.source,'direct sample 2');
elements.get('hint:revise-work').onclick();assert.equal(state.caseIndex,1);assert.equal(state.encounters[1].frames[1].work.source,'hint sample 1');
elements.get('tutor:direct').onclick();assert.equal(state.encounters[0].frames[1].work.source,'direct baseline');assert.equal(state.encounters[1].frames[1].work.source,'hint sample 1');
state.encounters=structuredClone(originals);context.render();elements.get('hint:revise-work').onclick();elements.get('policy-original-reply').onclick();assert.equal(state.encounters[1].frames[1].work.source,'hint baseline');assert.deepEqual(state.encounters[0].frames[0],originals[0].frames[0]);assert.equal(requests.length,1);
for(const status of ['tutor-error','tutor-pending','pending']){data.conditions[0].status=status;await elements.get('reload-policy-sampling').onclick();assert.equal(elements.get('tutor:direct').disabled,true);assert.equal(elements.get('direct:revise-work').disabled,true);const before=JSON.stringify(state.encounters);elements.get('tutor:direct').onclick();assert.equal(JSON.stringify(state.encounters),before);state.caseIndex=0;context.render();assert.match(elements.get('view-description').textContent,/No student action sampled/)}
data.authored_demo=false;await elements.get('reload-policy-sampling').onclick();assert.equal(elements.get('prototype-note').textContent,'Tutor policy sampling · Saved results');assert.match(elements.get('policy-sampling-distribution').innerHTML,/Observed model action frequencies/);assert.ok(requests.every(r=>r.opts.method===undefined));console.log('Policy sampling controller: condition isolation, next sample, baseline restore, reload reset, authored-data disclosure, failed/pending tutor guard, GET-only pass');})().catch(e=>{console.error(e);process.exitCode=1});
