// Authored adapter check: navigation stays in the existing workspace; no requests.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map();
const node=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',hidden:false,dataset:{},attributes:{},before(child){this.beforeNode=child},insertAdjacentHTML(){},setAttribute(name,value){this.attributes[name]=value},querySelectorAll(){return buttons}});return nodes.get(id)};
const stages=['captured','tutor','edit','execution','reaction'];
const buttons=stages.map((_,i)=>{const button=node('stage-'+i);button.dataset.trail=String(i);button.onclick=()=>{};return button});
const handlers=buttons.map(b=>b.onclick);
const saved={id:'direct',loop_example:true,loop_policy_label:'Direct answer',loop_sample:1,frames:stages.map(loop_stage=>({loop_stage,label:loop_stage}))};
const state={encounters:[saved],caseIndex:0,step:4};
let calls=0;
const context=vm.createContext({state,$:node,current:()=>state.encounters[state.caseIndex],document:{querySelector:node},glyph:()=>'<svg aria-hidden="true"></svg>',esc:String,notify:text=>{node('status').textContent=text},
  render(){calls++;node('#canvas .notebook-document > .notebook-caption').textContent='Workspace caption';node('#canvas .notebook-prompt').attributes={title:'Workspace prompt'}},
  renderOperationStatus(){node('.prototype-note').textContent='Generic status'},fetch(){throw Error('Adapter sent a request')}});
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../apps/student-loop.js'),'utf8'),context);
context.render();
assert.equal(state.step,0);
assert.equal(node('canvas').beforeNode,node('playback'));
assert.equal(node('trail-hint').textContent,'Step 1 of 5 · Saved sample 1');
assert.equal(node('loop-policy-row').hidden,true);
assert.equal(node('trail-title').textContent,'Interaction timeline');
assert.equal(buttons[3].attributes['aria-label'],'4. Local run · Researcher');
assert.equal(buttons[3].dataset.loopStage,'execution');
assert.match(buttons[0].innerHTML,/timeline-node/);
assert.deepEqual(buttons.map(b=>b.onclick),handlers,'Timeline preserves base playback handlers');
assert.equal(node('.prototype-note').textContent,'Saved student loop');
assert.match(node('#canvas .notebook-document > .notebook-caption').textContent,/No execution result at this stage/);
assert.equal(node('#canvas .notebook-prompt').attributes.title,'No execution result at this stage');
state.step=2;context.render();assert.equal(state.step,2,'Rendering preserves the selected stage');
assert.equal(node('trail-hint').textContent,'Step 3 of 5 · Saved sample 1');
state.step=3;context.render();
assert.match(node('view-description').textContent,/Researcher-triggered.*Actual local output.*No course grade/);
assert.equal(node('#canvas .notebook-document > .notebook-caption').textContent,'Workspace caption','Execution results stay with the existing renderer');
assert.equal(node('#canvas .notebook-prompt').attributes.title,'Workspace prompt');
state.step=4;context.render();assert.match(node('view-description').textContent,/new edit is unexecuted/);
saved.frames[4].status='no-reply';context.render();assert.match(node('view-description').textContent,/No message or code change/);
context.renderOperationStatus();assert.equal(state.step,4);assert.equal(node('.prototype-note').textContent,'Saved student loop');
saved.loop_authored_demo=true;context.renderOperationStatus();assert.equal(node('.prototype-note').textContent,'Authored test data · Saved student loop');
assert.equal(buttons[0].attributes['aria-label'],'1. Captured · Authored');
saved.loop_authored_demo=false;context.renderOperationStatus();assert.equal(node('.prototype-note').textContent,'Saved student loop');
assert.equal(buttons[0].attributes['aria-label'],'1. Captured · Recorded');
state.encounters=[structuredClone(saved)];context.render();assert.equal(state.step,0,'New verified data starts at the captured stage');
state.encounters.push({...structuredClone(saved),id:'hint',loop_policy_label:'Guided hint'});
context.render();assert.equal(node('loop-policy-row').hidden,false);
state.step=3;state.showInspector=true;state.selected='turn:7';node('run-details').open=true;
node('loop-policy').value='hint';node('loop-policy').onchange();
assert.equal(state.caseIndex,1);assert.equal(state.step,3,'Policy switching retains the same timeline stage');
assert.equal(state.showInspector,false);assert.equal(state.selected,'step');assert.equal(node('run-details').open,false);
assert.match(node('status').textContent,/Guided hint.*execution/);
node('loop-policy').value='missing';node('loop-policy').onchange();assert.equal(state.caseIndex,1);
state.refreshing=true;
node('loop-policy').value='direct';node('loop-policy').onchange();assert.equal(state.caseIndex,1);
assert.equal(node('loop-policy').value,'hint','Busy guard restores the displayed policy even before status rerenders');
context.renderOperationStatus();assert.equal(node('loop-policy').disabled,true);
state.refreshing=false;context.renderOperationStatus();assert.equal(node('loop-policy').disabled,false);
state.encounters=[];const previousCalls=calls;context.render();context.renderOperationStatus();
assert.equal(calls,previousCalls,'Empty data never enters the workspace frame renderer');assert.equal(node('playback').hidden,true);
assert.equal(node('loop-policy-row').hidden,true);assert.equal(node('loop-policy').disabled,true);
console.log('Saved student loop: preserved stage and navigation, policy switching, execution boundary, empty state, and no requests pass.');
